### PR TITLE
25 spot light shadow

### LINKED ISSUE #25: Add spot light shadows

### LINKED ISSUE #136: Directional shadow map is broken
See lights example:
screenshot 2019-01-18 at 15 38 49

### PR DESCRIPTION
**Pull request by dmnsgn**
- Update lights examples (add ambient light, rotate lights to spot depth issue)
- Add `updateSpotLightShadowMap` to renderer based on `updateDirectionalLightShadowMap` with a perspective projection
- Update sent spotlight uniforms to account for shadow map
- Update in shader Evaluate lights function in shader to pass the shadow map directly hence avoiding hardcoded `#if NUM_DIRECTIONAL_LIGHTS >= 8` light count checks
- Rename in shader `directionalShadow` to `getShadow`
- Add DEPTH_TOLERANCE (see https://github.com/pex-gl/pex-renderer/issues/136#issuecomment-474464619) as `if (depth >= far) return 1.0;` is not precise enough
- Add resource allocation dispose to spot-light component

Fix #25 Fix #136 

Further refactoring could be done but avoided for now to keep this PR simple.

### CODE REVIEW

**Comment by vorg** [comment]
Shadow map texture access has to stay unrolled due to MacBookPro 2017 Radeon 560 Pro bug https://github.com/pex-gl/pex-renderer/issues/32

Screenshot 2019-04-26 at 13 39 29

File: index.js [hunk 1]
```diff
@@ -232,6 +232,31 @@ Renderer.prototype.updatePointLightShadowMap = function (light, geometries) {
   })
 }
 
+Renderer.prototype.parseShader = function (string, options) {
```
Comment (dmnsgn) [inline index.js]: @vorg the regex has some constraints (don't mess up with spaces, need to replace the NUM_LIGHTS as well) but it is working fine. It should provide a tiny perf boost by not evaluating a for loop.
I opted to parse the shader only on program build, in order to call it only once and not every frame
